#! /bin/sh
FST=$1
CORPUS=$2
OUTPUT_FST=$3

# Temporary intermediate files
TEMP_DIR=".tmp"
mkdir $TEMP_DIR
ATTFST="$TEMP_DIR/transducer.att"
HFST_FST="$TEMP_DIR/transducer.hfst"
WEIGHTED_FST="$TEMP_DIR/weighted-pairs.hfst"
COMPOSED_FST="$TEMP_DIR/weighted-transducer.hfst"
MULTICHAR="$TEMP_DIR/multichar-symbols"
CLEANED_CORPUS="$TEMP_DIR/clean-corpus.tagged"

# Clean the input tagged corpus
sed -e '/^$/d' $CORPUS > $CLEANED_CORPUS
sed -i -e :a -e 's/:/__COLON__/;ta' $CLEANED_CORPUS
sed -i -e :a -e 's/__COLON__/\\:/;ta' $CLEANED_CORPUS

# Convert the input FST to HFST
lt-print $FST | sed -e 's/:/\\:/'| sed -e :a -e 's/ /\&#39;@_SPACE_@\&#39;/;ta'> $ATTFST
hfst-txt2fst --epsilon=ε -i $ATTFST -o $HFST_FST

LINES=$(wc -l $CLEANED_CORPUS | cut -d ' ' -f1)

# Prepare the multichar symbols files
awk -F '[<>]' '{print "<"$(NF-1)">"}' $CLEANED_CORPUS | tr -d , | sort | uniq > $MULTICHAR

# Generate a weighted FST from the string pairs
cat $CLEANED_CORPUS | sed -e 's/[ \t]//' | sed -e 's/\^.*\///' |
sed -e 's/\$$//' | sort | uniq -c | sed -e 's/^[ \t]*//' |
awk -v lines="$LINES" '{$1=-log($1/lines); print $2":" $2 "\t" $1}' |
hfst-strings2fst -j -o $WEIGHTED_FST -m $MULTICHAR

# Compose the input FST and the weighted FST
hfst-compose -1 $HFST_FST -2 $WEIGHTED_FST | hfst-fst2txt > $COMPOSED_FST

# Clean the composed FST for lt-comp
# Remove -- at any line and empty lines from the ATT file
sed -i -e 's/--//' $COMPOSED_FST
sed -i -e '/^$/d' $COMPOSED_FST

# Compile the FST back using lttoolbox
lt-comp lr $COMPOSED_FST $OUTPUT_FST

# Delete the temporary files
rm -rf $TEMP_DIR

